# ROS2 docker container
# that install ur drivers and rosbridge binaries
# and builds the FZI controller packages

ARG ROS_VERSION=galactic
FROM ros:$ROS_VERSION-ros-base
# the apt repository was very slow
# so change to mirrors
RUN sed -i 's/htt[p|ps]:\/\/archive.ubuntu.com\/ubuntu\//mirror:\/\/mirrors.ubuntu.com\/mirrors.txt/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-ur-robot-driver \
    ros-${ROS_DISTRO}-rosbridge-suite && \
    rm -rf /var/lib/apt/lists/*

# install the FZI controllers
# copy the source files
# install dependencies and run colcon build
SHELL ["/bin/bash", "-c"]

RUN mkdir -p /ros2_ws/src
COPY src/ /ros2_ws/src
WORKDIR /ros2_ws
RUN rosdep install --from-path . --ignore-src -y
RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --packages-skip cartesian_controller_simulation cartesian_controller_tests --cmake-args -DCMAKE_BUILD_TYPE=Release

